version: '3.8'
services:
  pgsql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    container_name: db_pgsql
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data

  redis:
    image: redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    stdin_open: true
    tty: true

  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    stdin_open: true
    tty: true
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=pgsql
      - POSTGRES_PASSWORD=password

  reverse_proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
