version: '3.8'
services:
  pgsql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    container_name: db_pgsql
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
  
  redis:
    image: redis
    ports: 
      - 6379:6379
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - 5000:5000
    stdin_open: true
    tty: true

  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=pgsql
      - POSTGRES_PASSWORD=password
