FROM ubuntu:latest

RUN apt update && \
    apt -y install curl && \
    curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh && \
    bash /tmp/nodesource_setup.sh && \
    apt install nodejs -y

EXPOSE 5000

WORKDIR /usr/app

COPY ./example-frontend /usr/app

ENV REACT_APP_BACKEND_URL="http://localhost:8080"

RUN npm install && \
    npm run build && \
    npm install -g serve

RUN useradd -m appuser && \
    chown appuser .

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]