version: '3.8'
services:
  pgsql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    container_name: db_pgsql
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis
    networks:
      - internal

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    stdin_open: true
    tty: true
    networks:
      - internal

  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    stdin_open: true
    tty: true
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=pgsql
      - POSTGRES_PASSWORD=password
    networks:
      - internal

  reverse_proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
    networks:
      - internal

networks:
  internal:
    driver: bridge
