FROM golang:1.16-alpine

EXPOSE 8080

WORKDIR /usr/src/app

COPY ./example-backend /usr/src/app

RUN apk update && \
    apk add --no-cache git gcc libc-dev && \
    go build && \
    go test ./... && \
    adduser -D appuser && \
    chown -R appuser:appuser .

ENV REQUEST_ORIGIN="http://localhost:5000"

USER appuser

CMD ["./server"]
