version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - 8080:8080
    stdin_open: true
    tty: true

