name: task_3_2

on:
  push:
    branches:
      - master
    paths:
      - 'exercises/task_3.02/**'

jobs:
  publish-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USER_DOCKER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: exercises/task_3.02/
          push: true
          tags: shalltearb1oodfallen/helsinki:latest

      - name: deploy to EC2
      - uses: actions/checkout@v2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
            HOSTNAME: 3.122.231.179
            USER_NAME: ubuntu

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              cd /home/ubuntu/ &&
              sudo docker run -d -p 80:80 shalltearb1oodfallen/helsinki:latest
              '

            
