name: task_3_1

on:
  push:
    branches:
      - master
    paths:
      - 'exercises/task_3.01/express-app/**'

jobs:
  publish-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USER_DOCKER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: exercises/task_3.01/express-app
          push: true
          tags: shalltearb1oodfallen/express-app:latest
