FROM golang:1.16-alpine AS build-stage

WORKDIR /app/src
COPY example-backend .
RUN CGO_ENABLED=0 GOOS=linux go build -o server .

FROM scratch AS run-stage

WORKDIR /app
USER 1000:1000

COPY --from=build-stage /app/src/server .

CMD ["/app/server"]

EXPOSE 8080
